//burger build related
export const ADD_INGREIDIENT = 'ADD_INGREIDIENT';
export const REMOVE_INGREIDIENT = 'REMOVE_INGREIDIENT';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const FETCH_INGREDIENTS_FAILED = 'FETCH_INGREDIENTS_FAILED'

//ordering burger
export const PURCHASE_BURGER_SUCCESS = 'PURCHASE_BURGER_SUCCESS';
export const PURCHASE_BURGER_FAIL = 'PURCHASE_BURGER_FAIL';
export const PURCHASE_BURGER_START = 'PURCHASE_BURGER_START';
export const PURCHASE_INIT = 'PURCHASE_INIT'

//order page
export const FETCH_ORDERS_START = "FETCH_ORDERS_START"
export const FETCH_ORDERS_SUCCESS = 'PURCHASE_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAIL = 'PURCHASE_ORDERS_FAIL';




